project:
  type: website
  output-dir: docs

website:
  title: "Aprende-R en español"
  site-url: dhumbertojs.github.io
  description: "Blog de trucos, curiosidades y mini tutoriales que he aprendido en mi experiencia para hacer del análisis de datos algo claro, sencillo y en español."
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/dhumbertojs
      - icon: twitter
        href: https://twitter.com/dhumbertoj
      - icon: journal-code
        href: https://www.r-bloggers.com/
format:
  html:
    theme: darkly
    css: styles.css



