project:
  type: website
  output-dir: docs

website:
  title: "blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/dhumbertojs
      - icon: twitter
        href: https://twitter.com/dhumbertoj
format:
  html:
    theme: cosmo
    css: styles.css



